name: CI

on: [pull_request]

jobs:
  rspec:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.0.6

    steps:
      - uses: actions/checkout@v1

      - name: Gem cache
        id: cache-bundle
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('**/Gemfile.lock') }}

      - name: Bundle install
        env:
          RAILS_ENV: test
        run: |
          BUNDLER_VERSION=$(cat .bundler-version)
          gem install bundler --version "$BUNDLER_VERSION"
          bundle _${BUNDLER_VERSION}_ install

      - name: Run tests
        env:
          RAILS_ENV: test
        run: |
          BUNDLER_VERSION=$(cat .bundler-version)
          bundle _${BUNDLER_VERSION}_ exec rspec
